/*-------------------------------------------------------------------- 
* Precompiled header source file used by Visual Studio.NET to generate
* the .pch file.
*
* Due to issues with the dependencies checker within the IDE, it
* sometimes fails to recompile the PCH file, if we force the IDE to
* create the PCH file directly from the header file.
*
* This file is auto-generated by qmake since no PRECOMPILED_SOURCE was
* specified, and is used as the common stdafx.cpp. The file is only
* generated when creating .vcxproj project files, and is not used for
* command line compilations by nmake.
*
* WARNING: All changes made in this file will be lost.
--------------------------------------------------------------------*/
#include "stdafx.h"
