#pragma once

#include "resource.h"

#define ERR_OK				0
#define ERR_UNKNOWN_TYPE	1
#define ERR_FILE_NOT_OPENED	2
#define ERR_UNKNOWN_CIPHER	3
#define ERR_WRONG_PASSWORD	4
#define ERR_KEY_REQUIRED	5
#define ERR_PRIVILEGE		6
#define ERR_INTERNAL		7
#define ERR_FILE_MAPPING	8
#define ERR_CREATE_EVENT	9
#define ERR_IMDISK_FAILED	10
#define ERR_IMDISK_TIMEOUT	11
#define ERR_UNKNOWN_COMMAND	12
#define ERR_MALLOC_ERROR	13
