#define IMDISK_RC_VERSION_STR    "2.0.10"
#define IMDISK_MAJOR_VERSION     2
#define IMDISK_MINOR_VERSION     0
#define IMDISK_MINOR_LOW_VERSION 10

#define IMDISK_RC_VERSION_FLD IMDISK_MAJOR_VERSION,IMDISK_MINOR_VERSION,IMDISK_MINOR_LOW_VERSION
