#ifndef UGLOBAL_H
#define UGLOBAL_H

#include <QtCore/QtGlobal>

#if defined(UGLOBALHOTKEY_LIBRARY)
#  define UGLOBALHOTKEY_EXPORT Q_DECL_EXPORT
#elif defined(UGLOBALHOTKEY_NOEXPORT)
#  define UGLOBALHOTKEY_EXPORT
#else
#  define UGLOBALHOTKEY_EXPORT Q_DECL_IMPORT
#endif

#endif // UGLOBAL_H
