# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ../../src/qtlockedfile.h \
    ../../src/qtlocalpeer.h \
    ../../src/qtsingleapplication.h \
    ../../src/qtsinglecoreapplication.h
SOURCES += ../../src/qtlocalpeer.cpp \
    ../../src/qtsingleapplication.cpp \
    ../../src/qtsinglecoreapplication.cpp
